before_install:
install:
    - git clone https://github.com/nsf/termbox.git
    - cd termbox
    - ./waf configure --prefix=usr
    - ./waf
    - sudo cp build/src/*so* /usr/lib/
    - sudo cp src/termbox.h /usr/include/
    - curl -s https://static.rust-lang.org/rustup.sh | sudo sh
script:
    - rustc --version
    - cargo build -v
    - cargo test -v
